services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      DOMAIN: ${DOMAIN}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgresql/${POSTGRES_DB}
      COOKIE_SECRET: ${COOKIE_SECRET}
      REDIS_URL: redis://:${REDIS_PASSWORD}@redis/0
      CLOUDINARY_NAME: ${CLOUDINARY_NAME}
      CLOUDINARY_KEY: ${CLOUDINARY_KEY}
      CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_REGION: ${AWS_REGION}

  postgresql:
    image: postgres:16.4
    container_name: baddit-postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - baddit-mobile-data:/var/lib/postgresql/data

  redis:
    image: redis:7.4.0
    container_name: baddit-redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - baddit-mobile-cache:/data
    

volumes:
  baddit-mobile-data:
  baddit-mobile-cache: